apiVersion: v1
kind: PersistentVolume
metadata:
  name: athena-create-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/.athenaCreate/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: athena-create-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local
